### ISSUE TITLE
大家不用看了，这个项目的星星都是刷，全是假的🤮

### ISSUE THREAD

**Issue by Cyamodus** [theajack/cnchar#100]
## 不用看了，这个项目的星星都是刷，全是假的

![snapshot](https://user-images.githubusercontent.com/64759181/80931941-92ee1c80-8def-11ea-897c-27cf0319d56a.png)

**Comment by TensortR** [comment]
什么玩意啊+1

**Comment by eslagy** [comment]
请好好做人🤥

**Comment by bop996** [comment]
恶心🤥

**Comment by eslagy** [comment]
骗子+1

**Comment by MoreWatcher** [comment]
是啊，太恶心了+2

**Comment by TensortR** [comment]
好恶心啊
