### ISSUE TITLE
哈哈，神奇，我点开一看，星星还真是都是刷的!

### ISSUE THREAD

**Issue by MoreWatcher** [theajack/cnchar#102]
## ![snapshot](https://user-images.githubusercontent.com/64759181/80931941-92ee1c80-8def-11ea-897c-27cf0319d56a.png) 

 太明显啦！
作者还是太年轻，请好好做人！

**Comment by eslagy** [comment]
一点开就发现星星都刷，顿时就恶心了，没意思🤐

**Comment by TensortR** [comment]
无耻+1

**Comment by SZ-LiuJF** [comment]
好恶心啊+1

**Comment by eslagy** [comment]
恶心他妈快给恶心开门啊，恶心到家了+1

**Comment by theajack** [comment]
就这么几个小号，评论就这么几句，能不能高端一点

**Comment by theajack** [comment]
真乖

**Comment by theajack** [comment]
不陪你聊了 继续哈 我希望一会看到1w个issue，这数据也是可以的
