### ISSUE TITLE
呵呵，还同济大学呢，学生就这个素质，不讲诚信！！

### ISSUE THREAD

**Issue by QQ14152289** [theajack/cnchar#103]
真是应该向学校举报你，丢人！学校和开源社区的耻辱！![snapshot](https://user-images.githubusercontent.com/64759181/80931941-92ee1c80-8def-11ea-897c-27cf0319d56a.png)

**Comment by SZ-LiuJF** [comment]
垃圾+1

**Comment by ITGangbang** [comment]
一点开就发现星星都刷，顿时就恶心了，没意思

**Comment by MoreWatcher** [comment]
什么玩意啊+2

**Comment by bop996** [comment]
一点开就发现星星都刷，顿时就恶心了，没意思

**Comment by Cyamodus** [comment]
一点开就发现星星都刷，顿时就恶心了，没意思+1
