### ISSUE TITLE
哈哈，神奇，我点开一看，星星还真是都是刷的

### ISSUE THREAD

**Issue by bop996** [theajack/cnchar#111]
## ![snapshot](https://user-images.githubusercontent.com/64759181/80931941-92ee1c80-8def-11ea-897c-27cf0319d56a.png) 

 太明显啦！
作者还是太年轻，请好好做人！

**Comment by Cyamodus** [comment]
一点开就发现星星都刷，顿时就恶心了，没意思

**Comment by bop996** [comment]
感到羞耻

**Comment by bop996** [comment]
请好好做人+1024
