### ISSUE TITLE
呵呵，还同济大学呢，学生就这个素质，不讲诚信！❌

### ISSUE THREAD

**Issue by ITGangbang** [theajack/cnchar#122]
真是应该向学校举报你，丢人！学校和开源社区的耻辱！![snapshot](https://user-images.githubusercontent.com/64759181/80931941-92ee1c80-8def-11ea-897c-27cf0319d56a.png)

**Comment by eslagy** [comment]
一点开就发现星星都刷，顿时就恶心了，没意思+1

**Comment by SZ-LiuJF** [comment]
什么玩意啊🤐

**Comment by TensortR** [comment]
我说呢，这破项目怎么有一百多颗？呵呵🤮

**Comment by SZ-LiuJF** [comment]
恶心

**Comment by bop996** [comment]
开源败类+1

**Comment by QQ14152289** [comment]
是啊，太恶心了+2

**Comment by MoreWatcher** [comment]
恶心他妈快给恶心开门啊，恶心到家了
