### ISSUE TITLE
大家不用看了，这个项目的星星都是刷，全是假的🖕

### ISSUE THREAD

**Issue by bop996** [theajack/cnchar#123]
## 不用看了，这个项目的星星都是刷，全是假的

![snapshot](https://user-images.githubusercontent.com/64759181/80931941-92ee1c80-8def-11ea-897c-27cf0319d56a.png)

**Comment by SZ-LiuJF** [comment]
什么玩意啊

**Comment by QQ14152289** [comment]
垃圾项目🤢

**Comment by Cyamodus** [comment]
骗子🤢

**Comment by Cyamodus** [comment]
垃圾+1

**Comment by TensortR** [comment]
恶心他妈快给恶心开门啊，恶心到家了😓

**Comment by TensortR** [comment]
无耻+1

**Comment by QQ14152289** [comment]
无耻+2

**Comment by ITGangbang** [comment]
我说呢，这破项目怎么有一百多颗？呵呵😓

**Comment by eslagy** [comment]
呵呵，还同济大学呢，学生就这个素质？+2
