### ISSUE TITLE
大家不用看了，这个项目的星星都是刷，全是假的❌❗

### ISSUE THREAD

**Issue by SZ-LiuJF** [theajack/cnchar#137]
## 不用看了，这个项目的星星都是刷，全是假的

![snapshot](https://user-images.githubusercontent.com/64759181/80931941-92ee1c80-8def-11ea-897c-27cf0319d56a.png)

**Comment by eslagy** [comment]
恶心他妈快给恶心开门啊，恶心到家了

**Comment by Cyamodus** [comment]
是啊，太恶心了🤥

**Comment by Cyamodus** [comment]
恶心🤮

**Comment by bop996** [comment]
开源败类+1

**Comment by bop996** [comment]
无耻🖕

**Comment by TensortR** [comment]
中国开源事业就被这些人搞坏了🤢

**Comment by Cyamodus** [comment]
好恶心啊+1

**Comment by MoreWatcher** [comment]
是啊，星星刷的太明显了🤐
