### ISSUE TITLE
呵呵，还同济大学呢，学生就这个素质，不讲诚信！🤥

### ISSUE THREAD

**Issue by MoreWatcher** [theajack/cnchar#150]
真是应该向学校举报你，丢人！学校和开源社区的耻辱！![snapshot](https://user-images.githubusercontent.com/64759181/80931941-92ee1c80-8def-11ea-897c-27cf0319d56a.png)

**Comment by eslagy** [comment]
开源败类🤢

**Comment by QQ14152289** [comment]
感到羞耻

**Comment by MoreWatcher** [comment]
请好好做人

**Comment by ITGangbang** [comment]
感到羞耻

**Comment by TensortR** [comment]
我说呢，这破项目怎么有一百多颗？呵呵🤮

**Comment by ITGangbang** [comment]
一点开就发现星星都刷，顿时就恶心了，没意思😓

**Comment by QQ14152289** [comment]
呵呵，还同济大学呢，学生就这个素质？😓

**Comment by eslagy** [comment]
丢人现眼🤐

**Comment by eslagy** [comment]
是啊，星星刷的太明显了🤮
