### ISSUE TITLE
大家不用看了，这个项目的星星都是刷，全是假的❌

### ISSUE THREAD

**Issue by Cyamodus** [theajack/cnchar#156]
## 不用看了，这个项目的星星都是刷，全是假的

![snapshot](https://user-images.githubusercontent.com/64759181/80931941-92ee1c80-8def-11ea-897c-27cf0319d56a.png)

**Comment by bop996** [comment]
是啊，太恶心了+2

**Comment by bop996** [comment]
垃圾

**Comment by TensortR** [comment]
一点开就发现星星都刷，顿时就恶心了，没意思
