### ISSUE TITLE
哈哈，神奇，我点开一看，星星还真是都是刷的🤥

### ISSUE THREAD

**Issue by MoreWatcher** [theajack/cnchar#162]
## ![snapshot](https://user-images.githubusercontent.com/64759181/80931941-92ee1c80-8def-11ea-897c-27cf0319d56a.png) 

 太明显啦！
作者还是太年轻，请好好做人！

**Comment by bop996** [comment]
请好好做人🖕

**Comment by Cyamodus** [comment]
骗子+2

**Comment by SZ-LiuJF** [comment]
无耻+1
