### ISSUE TITLE
支持多少汉字

### ISSUE THREAD

**Issue by Lyqxyz** [theajack/cnchar#170]

**Comment by theajack** [comment]
简体7000-8000 个左右，其中有繁体字的1300个左右

**Comment by theajack** [comment]
GB 2312标准共收录6763个汉字
基本覆盖了GB 2312标准

**Comment by hellonge** [comment]
> 简体7000-8000个左右，其中有繁体字的1300个左右

cnchar-draw有些字http.........json 404,有没有错误回调

**Comment by theajack** [comment]
@hellonge cnchar-draw 依赖第三方绘制数据 可能是会存在这个问题 可以举一个汉字例子吗
