### ISSUE TITLE
typescript import error

### ISSUE THREAD

**Issue by zhylmzr** [theajack/cnchar#172]
The `index.d.ts` syntax error: `A rest parameter cannot be optional.ts(1047)`

https://github.com/theajack/cnchar/blob/cfe294b910e1c1c9732034229a128defff37de67/src/main/index.d.ts#L17-L21

https://github.com/theajack/cnchar/blob/cfe294b910e1c1c9732034229a128defff37de67/src/main/index.d.ts#L49

**Comment by theajack** [comment]
@zhylmzr 
Thanks for your feedback, the bug has been fixed in version 2.2.1.
