### ISSUE TITLE
There is an unexpected result for Chinese character `任`.

### ISSUE THREAD

**Issue by plainheart** [theajack/cnchar#173]
Hi, this project brings a lot of help for Chinese projects, great!
Now there is a bug report.

---
**The detail**

Whatever the word is `任何` or `任意`, its tone is always `Rén`(wrong) rather than `Rèn`(right).
In fact, as we known, `Rén` is just used for surname or name of place, such as `任长霞`, `河北任丘`.

![image](https://user-images.githubusercontent.com/26999792/85000125-96155000-b184-11ea-99b5-cdf84b752d86.png)

Best Regards.

**Comment by theajack** [comment]
Thanks for your feedback, the default pronunciation of ‘任’ will be changed to ‘ren’, but there are currently no support for polyphonic characters in people’s names, such as ‘任’, ‘曾’, and I’m sorry for this.

**Comment by theajack** [comment]
Thanks for your feedback, the default tone of ‘任’ will be changed to ‘Rèn’, but there are currently no support for polyphonic characters in people’s names, such as ‘任’, ‘曾’, and I’m sorry for this.

**Comment by plainheart** [comment]
Thank you, I get it.
