### ISSUE TITLE
笔顺绘制模式的画布大小会受其他模式的干扰

### ISSUE THREAD

**Issue by aboutboy** [theajack/cnchar#174]
笔顺绘制模式type: cnchar.draw.TYPE.STROKE和其他模式一起使用的时候，比如和测验模式type: cnchar.draw.TYPE.TEST一起使用的时候，笔顺绘制模式的svg宽度会受到测验模式的影响。
比如笔顺绘制时我定义length为80，测验模式时为120，则笔顺绘制的笔顺大小为80，但svg画布宽度会变成120。
这是什么原因呢？
![image](https://user-images.githubusercontent.com/2050131/86761075-4b4a7200-c078-11ea-9d92-86b28ff9487f.png)

**Comment by aboutboy** [comment]
如果两次使用笔顺绘制模式的话，前一次的画布大小会被后一次影响。
![image](https://user-images.githubusercontent.com/2050131/86762190-0ffc7300-c079-11ea-8a43-b385d7019f0b.png)

**Comment by theajack** [comment]
@aboutboy 
感谢你的反馈，这是一个bug，已经修复了，请升级到v2.2.3使用

**Comment by aboutboy** [comment]
效率很高，谢谢！
