### ISSUE TITLE
cnchar.draw能否提供一个接口返回svg数据？

### ISSUE THREAD

**Issue by guguji** [theajack/cnchar#175]
这样子就可以在微信小程序中，通过把svg转base64的方式来显示了。

只是提个建议，目前其实并没有这样的需求，只是觉得如果有这样的接口会很棒，当然现在也很棒，非常感谢作者的开发能有这么棒的一个开源项目~

**Comment by theajack** [comment]
@guguji 
感谢你的关注
这个接口可以有，后续版本安排上

**Comment by theajack** [comment]
@guguji 
目前 cnchar-draw 仅支持在web环境下使用，微信小程序中使用请参考 [HanziWriter API](https://hanziwriter.org/docs.html#wechat-miniprograms)
