### ISSUE TITLE
获取汉字首字母拼音的问题

### ISSUE THREAD

**Issue by luoyuctl** [theajack/cnchar#178]
![image](https://user-images.githubusercontent.com/51604064/93050701-ef165680-f695-11ea-809c-741cb11b76bb.png)
'小区'.spell('first')的结果为什么是XO?应该是XQ才对

**Comment by theajack** [comment]
@GitSparkli 感谢反馈！区字是一个多音字，ou 是它的另一个读音。
这个问题已经在2.2.6版本中修复了，请升级使用。

**Comment by luoyuctl** [comment]
我使用的是在线引用的版本，可以把这个升级成2.2.6的吗?

**Comment by theajack** [comment]
@GitSparkli 
使用这个cdn  https://cdn.jsdelivr.net/npm/cnchar@2.2.6/cnchar.min.js

**Comment by luoyuctl** [comment]
@theajack 好的，谢谢
