### ISSUE TITLE
cnchar.stroke在微信小程序中调用的问题

### ISSUE THREAD

**Issue by syjhzfd** [theajack/cnchar#180]
您好，请问一下为什么cnchar.stroke在微信小程序中调用的时候返回的值为啥都是0呀，在浏览器中就不会出现这种问题。
![QQ图片20201010174236](https://user-images.githubusercontent.com/36884260/95651924-0d019a80-0b20-11eb-9db5-5d8784a3e080.png)

**Comment by theajack** [comment]
@syjhzfd 已修复，请升级到版本2.2.7使用
