### ISSUE TITLE
偏旁部首错误问题

### ISSUE THREAD

**Issue by xiayoutao** [theajack/cnchar#181]
半：不是 丶？
眝：不是 目？
冒：不是 冃？
耄耋：不是老？
有很多字的偏旁都有问题...

**Comment by theajack** [comment]
该库数据来源于网络，可能是会有错漏。
![image](https://user-images.githubusercontent.com/23377279/98194042-75923a80-1f59-11eb-8f6e-10618c098a49.png)
![image](https://user-images.githubusercontent.com/23377279/98194066-8347c000-1f59-11eb-8cac-a6ec646c3e68.png)
半和冒的是没错的。其他三个字我改正了，下个版本一起更新
