### ISSUE TITLE
这个怎么画 点横竖撇捺 等基本的笔画

### ISSUE THREAD

**Issue by soulge** [theajack/cnchar#182]
请问这个怎么画 基本的笔画？

**Comment by theajack** [comment]
你是指 横竖点 这些吗，跟调用绘制汉字一样的调用

`cnchar.draw('丿丨丿㇇|乛亅丿丶', {
    el: '#drawArea'
});`

![image](https://user-images.githubusercontent.com/23377279/102008597-beb18780-3d6c-11eb-97be-f71e90a5fb69.png)

![image](https://user-images.githubusercontent.com/23377279/102008603-cf61fd80-3d6c-11eb-92de-98342e16be72.png)

**Comment by theajack** [comment]
@soulge

**Comment by soulge** [comment]
是的，好像没有找到 捺折 还有其它一些 基本笔画。 只有 点横竖。。。 有什么方法可以自己定义吗？@theajack

**Comment by theajack** [comment]
你可以找找看[这里](https://github.com/theajack/cnchar/blob/master/src/plugin/order/stroke-table.json)有没有

如果没有你自己打出来或者去网上找到这个笔画 放到draw里去试试 如果不支持的话 就是库里没有这个符号的绘制信息，暂不支持定制

**Comment by theajack** [comment]
不知道你说的 捺折 是什么笔画 网上都搜不到，哪个汉字有这个笔画

**Comment by theajack** [comment]
@soulge

**Comment by soulge** [comment]
是 横，竖，撇，捺，横折，竖折，弯钩 等等 这些基本笔画。我想要展示一些最基础的笔画 而不是汉字。

**Comment by theajack** [comment]
@soulge 
这不就是最基本的笔画吗？ 你去 [这里](https://github.com/theajack/cnchar/blob/master/src/plugin/order/stroke-table.json) 找笔画的字符，然后调用 draw 画出来就是了
![image](https://user-images.githubusercontent.com/23377279/102016297-2088e600-3d9b-11eb-9a67-067a856f0fc0.png)

**Comment by theajack** [comment]
![image](https://user-images.githubusercontent.com/23377279/102016307-34cce300-3d9b-11eb-9377-11c8fb42dc7b.png)

**Comment by theajack** [comment]
目前只支持以下 七个笔画 
一丨亅丶丿乛乚
