### ISSUE TITLE
笔画绘制

### ISSUE THREAD

**Issue by lck8848** [theajack/cnchar#183]
draw绘制的偏旁有时候不准

**Comment by theajack** [comment]
哪些汉字能举个例子吗

**Comment by lck8848** [comment]
九







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tack Chen"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 下午4:20
收件人: "theajack/cnchar"<cnchar@noreply.github.com&gt;; 
抄送: "山の峰"<1370887376@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [theajack/cnchar] 笔画绘制 (#183)





 
哪些汉字能举个例子吗

**Comment by theajack** [comment]
抱歉 这个暂时无法提供笔画的绘制 我先close了 后面有时间在研究哈
