### ISSUE TITLE
打包后的资源存在ES6语法？

### ISSUE THREAD

**Issue by gottayan** [theajack/cnchar#184]
{t=r.initial[n],o=e.spell.substr(t.length);break}return{spell:e.spell,tone:e.tone,index:e.index,initial:t,final:o}};const u=(n,e,t)=>{if("object"!=typeof n)t(n,e);else for(const e in n)t(e,n[e])},c=n=>{const e=n.charCodeAt(0);return e>=19968&&e<=40869},p=(n,e)=>-1!==n.indexOf(e);const f=n=>{console.warn("CnChar Warning:"+n)};var h=t(3);const d=h,g="āáǎàōóǒòēéěèīíǐìūúǔùǖǘǚǜ*ńňǹ",y={array:"array",low:"low",up:"up",first:"first",poly:"poly",tone:"tone",simple:"simple",trad:"trad"};let m;function x(n,e){const t=e[0].split(""),o=e.splice(1);_("spell",o);const r=p(o,y.poly),i=p(o,y.tone),a=[];for(const e in n){const o=n[e],s=parseInt(o[0]);for(let n=0;n<t.length;n++){const l=t[n];if(c(l)){let u=o.indexOf(l);if(-1!==u){const c=C(e,o,u,r,i,s);if(c.poly){a[n]||(a[n]=[]),a[n].push(c.res);let t=o;const p=t.match(new RegExp(l,"g")).length;for(let o=1;o<p;o++)t=t.substr(u+2),u=t.indexOf(l),a[n].push(C(e,t,u,r,i,s).res)}else c.isPolyWord&&d[l]&&(c.res=O(d[l],i).spell),a[n]=[c.res],t[n]=""}}else""!==l&&(a[n]=["NOT_CNCHAR",l])}}k(a,o);const s=[];for(let n=0;n<t.length;n++){const e=a[n];void 0===e?s[n]=t[n]:e.length>1?"NOT_CNCHAR"===e[0]?s[n]=e[1]:s[n]=`(${a[n].join("|")})`:s[n]=e[0]}return p(o,y.array)?s:s.join("")}const k=(n,e)=>{m._.poly&&w(n,T),p(e,y.first)&&w(n,b),p(e,y.up)?w(n,z):p(e,y.low)||w(n,j)};function w(n,e){n.forEach((t,o)=>{"string"!=typeof t?"NOT_CNCHAR"!==t[0]&&t.forEach((n,o)=>{t[o]=e(n)}):n[o]=e(t)})}function b(n){return n[0]}function z(n){return n.toUpperCase()}function j(n){return z(n[0])+n.substr(1)}function T(n){return n.toLowerCase()}function C(n,e,t,o,r,i){let a=parseInt(e[t+1]);const s={res:n,poly:!1,isPolyWord:a>=5};return o||r?(s.isPolyWord&&(a-=5,o&&(s.poly=!0)),r&&(s.res=S(n,i,a)),s):s}const O=(n,e)=>{if(e)return{spell:n};for(let e=0;e<n.length;e++){const t=g.indexOf(n[e]);if(-1!==t)return{spell:n.substr(0,e)+"aoeiuün"[Math.floor(t/4)]+n.substr(e+1),tone:t%4+1,index:e+1}}return{spell:n,tone:0,index:-1}};function S(n,e,t){if(0===t)return n;const o=n[e],r=g[4*"aoeiuün".indexOf(o)+(t-1)];return o!==r?n.replace(o,r):n}function v(n,e){const t=e[0].split(""),o=[],r=e.splice(1);_("stroke",r);for(const e in n)for(let r=0;r<t.length;r++)t[r]&&-1!==n[e].indexOf(t[r])&&(t[r]="",o[r]=parseInt(e));return t.forEach((n,e)=>{n&&(o[e]=0)}),p(r,y.array)?o:W(o)}const W=n=>{let e=0;return n.forEach((function(n){e+=n})),e};let q=!1;const _=(n,e,t)=>{if(!m.check)return;if(q)return void(q=!1);t&&(q=!0);const o=[];for(let t=e.length-1;t>=0;t--){const r=e[t];m.type[n][r]||(o.push(r),e.splice(t,1))}const r=[],i=[],a=(n,t=r)=>{n instanceof Array?n.forEach(n=>{a(n,t)}):p(e,n)&&t.push(n)};-1===m.plugins.indexOf("trad")&&(p(e,"simple")&&r.push("simple"),p(e,"trad")&&r.push("trad")),"spell"===n?

const =>箭头函数

**Comment by theajack** [comment]
还真是 可能是升级ts之后忘了修改babelrc了
我处理一下

**Comment by gottayan** [comment]
> 还真是 可能是升级ts之后忘了修改babelrc了
> 我处理一下

我还在clone你的代码哈哈

**Comment by theajack** [comment]
@gottayan 
已修改打包配置 情升级到v3.0.1使用

**Comment by gottayan** [comment]
> @gottayan
> 已修改打包配置 情升级到v3.0.1使用

好的
想请教个问题

{
        test: /\.js$/,
        use: ['cache-loader', 'thread-loader', 'babel-loader'],
        // exclude: /node_modules\/(?!.*cnchar|.*cnchar-trad).*/,
        include: [path.join(__dirname, '..', 'public'), path.join(__dirname, '..', 'node_modules/cnchar'), path.join(__dirname, '..', 'node_modules/cnchar-trad')],
      },
      
      一开始想把node_modules的包放到webpack打包 但是这样不生效？为什么？

**Comment by theajack** [comment]
@gottayan 
`
{
    test: /.js$/,
    use: ['cache-loader', 'thread-loader', 'babel-loader'],
    exclude: /node_modules\/(?!(模块名)\/).*/,
},
`

**Comment by gottayan** [comment]
就是这样加的 但是不生效 打包还是存在



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tack Chen <notifications@github.com&gt;
发送时间: 2021年1月2日 12:09
收件人: theajack/cnchar <cnchar@noreply.github.com&gt;
抄送: gottayan <1174930941@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[theajack/cnchar] 打包后的资源存在ES6语法？ (#184)





 
@gottayan
 { test: /.js$/, use: ['cache-loader', 'thread-loader', 'babel-loader'], exclude: /node_modules\/(?!(模块名)\/).*/, },

**Comment by theajack** [comment]
@gottayan 
我是试过了可以的，那我就不清楚了
 你和我的写法不一样的 你重新把我发的copy过去试试？

**Comment by gottayan** [comment]
我copy的 也不行。
你可以发你的demo我看下吗 建个GitHub 可能是某些版本不一致导致的。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tack Chen <notifications@github.com&gt;
发送时间: 2021年1月2日 20:58
收件人: theajack/cnchar <cnchar@noreply.github.com&gt;
抄送: gottayan <1174930941@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[theajack/cnchar] 打包后的资源存在ES6语法？ (#184)





 
@gottayan
 我是试过了可以的，那我就不清楚了
 你和我的写法不一样的 你重新把我发的copy过去试试？

**Comment by theajack** [comment]
@gottayan 
改天哈 那个电脑不在身边

**Comment by gottayan** [comment]
好的感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tack Chen <notifications@github.com&gt;
发送时间: 2021年1月2日 21:09
收件人: theajack/cnchar <cnchar@noreply.github.com&gt;
抄送: gottayan <1174930941@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[theajack/cnchar] 打包后的资源存在ES6语法？ (#184)





 
@gottayan
 改天哈 那个电脑不在身边

**Comment by gottayan** [comment]
{
        test: /\.js$/,
        use: ['babel-loader'],
        exclude: /node_modules\/(?!(cnchar|cnchar-trad)\/).*/,
      }







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "theajack/cnchar"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月2日(星期六) 中午12:09
收件人:&nbsp;"theajack/cnchar"<cnchar@noreply.github.com&gt;;
抄送:&nbsp;"崔家奇"<1174930941@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [theajack/cnchar] 打包后的资源存在ES6语法？ (#184)





 
@gottayan
 { test: /.js$/, use: ['cache-loader', 'thread-loader', 'babel-loader'], exclude: /node_modules\/(?!(模块名)\/).*/, },

**Comment by theajack** [comment]
@gottayan 
发到你qq邮箱了

**Comment by gottayan** [comment]
好的 感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tack Chen <notifications@github.com&gt;
发送时间: 2021年1月5日 12:04
收件人: theajack/cnchar <cnchar@noreply.github.com&gt;
抄送: gottayan <1174930941@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[theajack/cnchar] 打包后的资源存在ES6语法？ (#184)





 
@gottayan
 发到你qq邮箱了
