### ISSUE TITLE
这个库可以高亮字的笔画吗？

### ISSUE THREAD

**Issue by soulge** [theajack/cnchar#185]
我想要高亮一个字的具体哪一个笔画 查了一下hanziwriter好像只能高亮部首，请问你这个库可以实现这个功能吗？

**Comment by theajack** [comment]
@soulge 
只能像这样以笔顺的形式高亮最后一笔
![image](https://user-images.githubusercontent.com/23377279/104865485-17310180-5977-11eb-8894-e195b24ab9e3.png)

另外 cnchar-draw 插件是基于hanziwriter 封装的
