### ISSUE TITLE
cnchar.spell('成都') => ChengDou 

### ISSUE THREAD

**Issue by thiszhong** [theajack/cnchar#188]
![20210220140921](https://user-images.githubusercontent.com/12380965/108585785-4aefb480-7385-11eb-88b4-1a3b6f241d74.jpg)

是不是应该是 `ChengDu` 呀

**Comment by theajack** [comment]
@thiszhong 多音词支持需要引用 cnchar-poly 库

```js
import cnchar from 'cnchar';
import poly from 'cnchar-poly';
cnchar.use(poly);

cnchar.spell('成都');
```

![image](https://user-images.githubusercontent.com/23377279/108586884-0582b580-738c-11eb-8af8-c211263a87b3.png)
