### ISSUE TITLE
革命的革 输入转换出来的是Ji，引用的是cnchar.min.js

### ISSUE THREAD

**Issue by yue-f** [theajack/cnchar#189]
输入转换出来的是
![image](https://user-images.githubusercontent.com/33945064/112788214-efec6400-908c-11eb-84ca-4542acb719a0.png)

**Comment by theajack** [comment]
@yue-f 
感谢反馈，后续的版本会优化这个
可以先使用 `cnchar.setSpellDefault('革', 'ge2')` 做个兼容

**Comment by yue-f** [comment]
请教个问题，如果遇到多的多音字的话，是需要每一个都手动设置吗？

**Comment by theajack** [comment]
@yue-f 
引入 cnchar-poly 库就可以支持多音词，如果有疏漏的话，需要自己设置，设置多音词不是用我刚发的那个api，用的是这个 `cnchar.setPolyPhrase('你好', 'ni3 hao3')`

请参考 [https://theajack.gitee.io/cnchar/doc/poly.html](https://theajack.gitee.io/cnchar/doc/poly.html) [https://theajack.gitee.io/cnchar/doc/custom.html#_6-%E8%AE%BE%E7%BD%AE%E5%A4%9A%E9%9F%B3%E8%AF%8D%E7%9A%84%E8%AF%BB%E9%9F%B3%EF%BC%9Asetpolyphrase](https://theajack.gitee.io/cnchar/doc/custom.html#_6-%E8%AE%BE%E7%BD%AE%E5%A4%9A%E9%9F%B3%E8%AF%8D%E7%9A%84%E8%AF%BB%E9%9F%B3%EF%BC%9Asetpolyphrase)

**Comment by yue-f** [comment]
好的，谢谢
