### ISSUE TITLE
Wrong spelling in cnchar-poly

### ISSUE THREAD

**Issue by guoyou** [theajack/cnchar#190]
画栋朝飞南浦云，珠帘暮卷西山雨
huà dòng cháo fēi nā pǔ yún ， zhū lián mù juàn xī shān yù.

The third character's spelling must be 'zhāo', and the eleventh character's spelling must be 'juǎn'

**Comment by theajack** [comment]
对于古诗词和文言文，目前尚不支持
可以使用 `cnchar.setPolyPhrase` api 定制拼音
[请参考文档](https://theajack.gitee.io/cnchar/doc/custom.html#_6-%E8%AE%BE%E7%BD%AE%E5%A4%9A%E9%9F%B3%E8%AF%8D%E7%9A%84%E8%AF%BB%E9%9F%B3%EF%BC%9Asetpolyphrase)
