### ISSUE TITLE
“归” 获取首字母错误

### ISSUE THREAD

**Issue by AHopes** [theajack/cnchar#191]
![image](https://user-images.githubusercontent.com/19965547/123721217-6715dc00-d8b8-11eb-9dbe-8c699aaba336.png)
“归” 获取首字母错误

**Comment by theajack** [comment]
感谢您的反馈 目前可以使用  `cnchar.setSpellDefault('归', 'guī');`  做一下兼容处理
该修复会随着下个版本一起发布

**Comment by theajack** [comment]
已添加 请升级到 3.0.2 使用
