### ISSUE TITLE
使用HanziWriter中的某些字调用stroke('order','name')方法后得到undefined

### ISSUE THREAD

**Issue by xiatian12345** [theajack/cnchar#192]
成功个数 8075 失败汉字如下 [
  '⺀', '⺈', '⺊', '⺌', '⺍', '⺗', '⺮', '⺳', '⺼', '㐆',
  '㐌', '㐬', '㐭', '㐱', '㒸', '㒼', '㓞', '㔾', '㕡', '㝵',
  '㠯', '㡭', '㢆', '㢟', '㣎', '㥯', '㧜', '㬎', '㲋', '㳄',
  '㼌', '㿽', '䍃', '䕭', '䙴', '䜌', '䠀', '䧹', '䰾', '䴉',
  '丂', '丄', '丏', '丨', '丩', '丬', '丱', '丵', '丶', '丷',
  '丿', '乑', '乚', '乛', '乶', '乹', '乿', '亅', '亙', '亠',
  '亶', '亹', '亼', '亾', '仌', '伄', '伕', '伾', '佇', '佉',
  '併', '佽', '侌', '侷', '係', '俉', '俛', '倀', '倖', '倝',
  '倞', '倠', '倻', '偽', '傕', '傖', '傚', '傢', '傯', '傿',
  '僂', '僉', '僕', '僱', '儂', '儅', '儕', '儘', '儷', '儸',
  ... 1399 more items
] 一共失败 1499 个。

**Comment by theajack** [comment]
抱歉 对于某些生僻字和繁体字 确实字典中不存在它们的笔顺

**Comment by xiatian12345** [comment]
好的，那我关闭该问题了哈
