### ISSUE TITLE
宝盖头第二笔是啥？

### ISSUE THREAD

**Issue by edonlu** [theajack/cnchar#193]
`cnchar.stroke('宝', 'order', 'name'),`输出`点,撇点,横撇|横钩,横,横,竖,横,点`，第二笔是`撇点`。
`cnchar.stroke('宝', 'order', 'shape'),`输出`丶,㇀,㇇|乛,一,一,丨,一,丶`，第二笔是`㇀`？
可是`cnchar.orderToWord.orders`里面的撇点对应的是`𡿨`。
用`cnchar.orderToWord(['点', '撇点', '横钩'], 'start'),`不能输出宝盖头的字。

所以宝盖头第二笔是啥？

**Comment by theajack** [comment]
已修复 宝字第二笔名称改为 点2
