### ISSUE TITLE
“谷”字首字母出错，识别为Y

### ISSUE THREAD

**Issue by yywdandan** [theajack/cnchar#196]
![gu](https://user-images.githubusercontent.com/74121994/128803820-e88ea148-3bc6-48b6-ad99-7c8d3f32db8d.png)

**Comment by theajack** [comment]
@yywdandan 感谢您的反馈 下期版本带上这个错误修复

**Comment by theajack** [comment]
@yywdandan 
可以先使用以下方法自定义数据使用 
`cnchar.setSpellDefault('谷', 'gǔ')`

**Comment by theajack** [comment]
已经添加 可以升级到 3.0.4 使用
