### ISSUE TITLE
spell-dic-jian 说明

### ISSUE THREAD

**Issue by mapull** [theajack/cnchar#198]
在 spell-dic-jian.json 文件里

	"hei": "1:黑1嗨6嘿6",
	"ng": "0:嗯9嗯7嗯8",

像上面这样的是什么意思，作者能说明一下吗？

hei 是读音能看懂，**1:** 是什么意思，还有这个 **嗯9嗯7嗯8** 为啥要这样写？

因为在使用的时候，发现很多音问题，特别是多音字的默认音。因此打算研究一下代码。

将军 ：qiāngjūn
是否：shìpǐ
长不大：chángbùdà
单于：chányú （这个是对的）

cnchar 当前最新版，参数 spell('low','tone')

**Comment by theajack** [comment]
"hei": "1:黑1嗨6嘿6",

hei 表示的是无音调拼音，后面的第一个1表示音调的位置，从0开始的
每个汉字后面跟的数字表示音调 0-4 分别表示轻声到一二三四声，5-9也分别表示轻声到一二三四声，区别是大于等会5的汉字表示的是它是一个多音字。

第二个问题

将军 ：qiāngjūn
是否：shìpǐ
长不大：chángbùdà

cnchar-poly 插件识别多音词组依赖的是多音词词典（polyphone-phrase-simple.json）
由于词非常多，所以对于多音词只对不常见的读音的常见词组进行收录
将 jiang 和否 fou 字就是多音字的常见读音，应该收录于 spell-default.json 文件，但是由于疏漏没有收录，后续会补上
至于 长不大 这种不属于常见词组，基于这种可以扩张出 长不长，长不胖，长不高 等一大堆词，依赖词典分辨是不大可能的

所以前面两个可以通过后续fix 增加默认读音解决，第三个没办法准确分辨拼音。

**Comment by theajack** [comment]
@mapull

**Comment by mapull** [comment]
@theajack 感谢这么快的回复。找了很多拼音库，这个库在功能的丰富度、API的完善度、文档的清晰度上都表现的相当不错。唯一遗憾的是，拼音的准确度不尽如人意，还有很大的改进空间。
还有一点，库的LICENSE是 MIT 的，可以在Readme最后说明一下，免除使用的后顾之忧。

我会经常来把收集到的错误音标提出来，期待拼音的识别率越来越高。

**Comment by theajack** [comment]
@mapull 感谢你的反馈与认可

**Comment by theajack** [comment]
对于 长不大 这种词组可以使用 setPolyPhrase 方法定制拼音
![image](https://user-images.githubusercontent.com/23377279/136681134-845589bb-f5ad-4c6a-bb65-ca321c1a1182.png)

还有其他[自定义数据的方法](https://theajack.gitee.io/cnchar/doc/custom.html)可以使用
@mapull
