### ISSUE TITLE
汉字绘制功能在vue中怎么用

### ISSUE THREAD

**Issue by hellonge** [theajack/cnchar#201]
和在微信小程序使用方式一样吗

**Comment by theajack** [comment]
不一样 目前没有封装基于vue的组件 只能使用 api + vue ref 的方式 [api](https://github.com/theajack/cnchar#52-%E5%8F%AF%E8%A7%86%E5%8C%96%E7%BB%98%E5%88%B6%E6%B1%89%E5%AD%97-draw)
```html
<div ref='container'>
</div>
```

```js
cnchar.draw('你好', {
    el: this.$refs.container
})
```
小程序请参考 [小程序使用](https://github.com/theajack/cnchar#524-%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%B8%AD%E4%BD%BF%E7%94%A8)
