### ISSUE TITLE
不准确的多音字

### ISSUE THREAD

**Issue by Hefr-y** [theajack/cnchar#204]
中国银行行长

pinyin with tone: Zhōng,Guó,Yín,Háng,***Xíng**,Cháng

行长

pinyin with tone: ***Xíng**,Cháng

**Comment by theajack** [comment]
感谢反馈，后续会加上这个多音词

**Comment by theajack** [comment]
cnchar.setPolyPhrase('行长', 'hang2 zhang3')
@Hefr-y  可以暂时使用这个api 指定多音词读音
