### ISSUE TITLE
“柴”多音字选择问题

### ISSUE THREAD

**Issue by zungmou** [theajack/cnchar#205]
程序给出的结果是：Zhài
常见的都是：Chai

程序是否给多个结果？

**Comment by theajack** [comment]
@zungmou 感谢反馈 这个该多音字默认读音的遗漏
可以使用 cnchar.setSpellDefault('柴', 'chái') 指定默认读音
也可以使用 cnchar.spell('柴', 'poly', 'tone') 获取全部读音

这个字的默认读音会在后续版本带上
