### ISSUE TITLE
网络不好加载字体json失败

### ISSUE THREAD

**Issue by LEIHD** [theajack/cnchar#206]
因为网络不稳定导致请求字体对应的json文件失败，有没有直接引入离线字体文件的解决方案

**Comment by theajack** [comment]
感谢你的反馈 这个后续会考虑加入更新计划的

**Comment by theajack** [comment]
3.1.0 已支持该功能，请参考 [离线使用和自定义部署](https://theajack.github.io/cnchar/doc/offline.html)
