### ISSUE TITLE
ts ICnChar 接口上方法数量有限

### ISSUE THREAD

**Issue by PullAndRun** [theajack/cnchar#207]
安装cnchar-all之后，文档里类似convert的方法调用不出来

**Comment by theajack** [comment]
感谢反馈 后续会加入修复计划的

**Comment by theajack** [comment]
你可以试试[这里](https://theajack.gitee.io/jsbox/?github=theajack.cnchar@master)

是有convert对象的

你是不是指没有代码提示

**Comment by theajack** [comment]
已修复 请升级到3.0.6使用
