### ISSUE TITLE
繁體  鐘  字無法找到.

### ISSUE THREAD

**Issue by abin2011** [theajack/cnchar#216]
因為要計算姓 鐘 的有多少筆畫, 發現沒有鐘字, 請問可否添加到繁體庫中呢. 因為百家姓裡 也有這個字

**Comment by theajack** [comment]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/23377279/160958825-5c8a8773-81bd-4b01-af3f-47d085477f39.png">

有的哈 [前往](https://theajack.gitee.io/cnchar/#%E9%8D%BE)

**Comment by theajack** [comment]
可能你没有引用cnchar-trad 库？

**Comment by abin2011** [comment]
![image](https://user-images.githubusercontent.com/1227434/163510621-266e58ca-a365-47cb-bd97-469226e566df.png)
比較奇怪, 我這邊輸入 鐘 字 看不了筆畫.我看了瀏覽器也沒有報錯.
Chrome 100

**Comment by abin2011** [comment]
原來 繁體的 鍾 姓 不是 鐘

**Comment by theajack** [comment]
<img width="102" alt="image" src="https://user-images.githubusercontent.com/23377279/169495773-be64c3d9-dc03-4851-9bcb-6025f3c8658b.png">
两个都是
