### ISSUE TITLE
为啥粥会返回 Y 呢。。。

### ISSUE THREAD

**Issue by leonahliang90** [theajack/cnchar#218]
<img width="226" alt="image" src="https://user-images.githubusercontent.com/4065175/159893422-ea9a45ca-09a9-4881-a9f1-746992f3d8f7.png">

**Comment by theajack** [comment]
<img width="858" alt="image" src="https://user-images.githubusercontent.com/23377279/160957905-3e97a93b-7e65-42ea-878d-8bbfff15d213.png">

可以检查一下你的版本哈 3.0.5 应该是没问题的
