### ISSUE TITLE
有很多繁体字笔画都是0，比如宁转繁体是寧后，返回的笔画数是0

### ISSUE THREAD

**Issue by guoyili209** [theajack/cnchar#223]
cnchar.stroke(cnchar.convert.simpleToTrad('宁'))；//0

**Comment by theajack** [comment]
感谢反馈，还有发现其他字吗 后续一起加一下

**Comment by guoyili209** [comment]
宁炜缪窦栾祯玺台晔韬轶烨历恺郦珑鸾鑑鹭俤侬彐骧琏粦炀骊铙骝跻俪焘迺鹂亘阗诤绫岺迹暧凃雳俦傥谛苳勍鎌皊廼厘轸徕绐颋郞讷崙婻蛲斓赉曽崚辂锜辇绨烺昙玠鸫呐遆鹞缇钬暘砀岊饧炖嶋鍊钅趸缭煖娲叹勣褟袛熖玪绦迩榎厐洊燐烔炆畠抟鸷毜鸰鏐燿胧阆瀬瑱冏亷鲡廪纣琭枬玨喨爔瑯畇蓸瑮矞骎颙漋璆诶纨煋懃竻燏暻芶倞慬駺飔镠騄錬肈龛呖玓逎焵媞焌曺埰麐棨凊騋嫤捲堦姢诋贽殚胪鹧籴夌鶄埌泆驄柾斳嫕姎闕娳媮瞈埻滝絿汧焮噜辘鹈跞屴鲇鹨鲮驽驎裣轺谠媁稆袓悰瓅宭舲鄗椂掦玘瓈廸瑨泂倢樫仼鄔継惪珰俍苙玱骕靑谲睐慆炝咛辚懔耹畯籣儷銭矴荅鏦鄌妉洤碻鵷莙橉璪熺禢袺爕萳孄煐蕳峝澯蔵耑觧熲漻嵒臤鮀褛藟珟柮碕憇烇逦鼗鲈艻胨鞑鸸缡焖鸩逴雠辍躏旂婈弇朸斉唫籙湝濓鵃聡姉錂晙磾銡羕矱諵祘鞦旿瑫鴼歏玝穠廘籐粬墻敭嵜陖捁垱遰琱榤桹籧駉烱娚碐絳頲湶砳趯姾烒玴烻瑔靔嚥熷裫璻耺杕禭鴒嬝伒俫輗煒钁伈婍颎枏昤燡谘骓髅偻轹绺舻哝疬叆艹侓蛏耧齑佁赕辏玦谪赀裆晊繅嫀橾鶆娞簵稑溍謰囉灆褸塙璄櫺羈驥稘埧嶻誳濈礌鐫旔巔筜婃嗹跡毻驌雋泇昽楴綅朥縯囈勚喒臢鹔琁寗隣繚竫捛曁縢熼才钊钰铨鉴铎婵铮骥谌銮钜阙钿钗铿镛铉钏锴锟骁姗谯锵哓靓出禅锷镔铖镝轼诏铠镒铧镖钭禇钺钩闾钤驷钵咨绶镯钲瓒谕钫剀铢皂镡虓铄瑢镗骢琤掁礽赪缜锬纾厍闩铵铫钶钛镳铤镏睒刿锂嫱颞钹鈺镪铷俣锶甡暎颛勲錶伧鋕锏镨谡钴阕镱旵録瑒赜愔铛钍粧貟镅侪铳钋誌鉏镫镌镓钐煕锆锫铋钸钇锃骍锠鎔谒锝稣媖缷瑧钖娬顕辻锲铌镦轫铼啧铟錡悫晹侴釗锒诜锢伫钔锖镘钕钼郤蚬銧釵铈褆靭锱谵籼绉锘钽锎觎釴怣莦咮嫄勛卲錾铯骖镧刍翾訚尙鷟铕伭锍偰跹锛狲锞戗驺谖燨姹橖鉦餘禔伩熈戋栀伥铑钣镥弌铪阋柟瑃嫆週瑆兟蔯顏鶠奓辀珎禕卋鈡汌挻璕賙姺镤鲳镬忏阊鹾绡镂鲭粽锾鏻絷蛳铇斎鐘伃颺晛錩効婋羜瀋煁瀞倖妟宧琋郷晅祅璓憗俙諝玔愃诹丗鋹鸶蝾镎怅紬錞讪锨円锓鑚箎珹鎗晱妡琓竚阠侲謓詔込庒蒒昡迠鍟鉵悕脇姸璿粻姁骃媗盺靱姙勷嫈锼聍黩骣糍锉谥鍼绌扌帱缛馓扆鎧釪赬鍈窚遹嬑棯鉋斅驙鍝豙縿鉉襭馫祫毧璽鎕銉駪趈骦烋鉖桭鏕嬋菭踰橦鈃宍輮鈱翛詡係铔緻昫媜銍辶鎚瓀伝晳玿瑑鋖栦騂卨唢琸趱驵佀殇鸺谂糁锔铗觇冁锪伡锕鳝缐穇镲鐇觞惬卂恸镟谇咝綵镞鐏蹑镆鰆揗媭晢銾敔鉁鹢姌尗笘埘鑤伳壵锳鹴鈛罌兿嚮艷晫頣暿諶儳毚実縀羶鉥彣騱釚鋳癒晸鈄媟忎睎珃旑鍚嚐椙畼嘨荿埩剄燸鉐銣鑾暁銤嫰觪贳瓖陭松群颜邝栗蔺桦桢阚绮笃莺隽骞鲲荪颉骐帼郏轲鹄霭颢槟荟赓荘荛戬诠呙俨诰虬枞桠莅玑颀床驿苌俆挂签谏缙枭郐箫栎枧芗愷觐蒉桧纭苋蒨绛兖袆杠鹍柽蕲莳檩椤樯谔荞橹萦茏荩劻觊诘缃荭翬鵾莼雇苘筝秾妩缵枨飓皞榇榄蒌鹗蓥贶昵熀崐苾荦哜玕佥妫広衮栊皲辁籁闳桡杩絖苎荠茑榉鹫羁鹪撷琯鹆梽骙蓦笕瓘忾煃晧暉珖莴棂纮亁笹紘槠穑鲠黉竤棡侊熇寛稙穂暤煇梶迳纩姖閤荁橞蕰畊簷缟鲛鲒筴蘖鳄枥赇跷鹬茀榟鑛篠藴芠棫爀缰掴栉苈梼讦矼鈜萓枟灴苪浤苧茽矦熩櫛玒啬喾箦脍弪绲鞒鹘鸪笾戆哙鸹枊橼箪馑讧叽鳅绻饫苁薮婳掛荗杊嘠篤恵菓蒑蓠椟绔蓣桤阒诂晖郁闵汇飚骅么灏潇贲秘谟颍霁滢珲缑浒飙浔泾闲娆娒濑飒泸骈奂仆绯沣浏泷嫔渌劢缤抛滟洑辟哗浈膑鸠傧涞荥谧湜骠湿绂芈泺濬沄沢浍溆邠诃骉缦渼冮媄琲渑豊玭湲褔沩潆浥渎诨颦満纰禀澐澔鳆湣偑瑂凎凫颌氵淏唇懑绗饷溁雱祃鳍驸涠馄忞僕霙溎溦淯滉凶汎玶妼湑洨浬皛犎眀沺暋瀟鲺滠鳘偾鳖钚颃黾鲆鲞霂瑸淾沯玧雫蓂郃轷婓麃鳔飑唛罴阍鹁仌滈渖渶訸阌掽媺雺铓淜昞婔颿裵渂勄阝妺颔缥缋瀿氿浛麽灝鲋顸殡麸鹱鹕赙沨鲩鳗扪潋鲨鹛鲟妘牦塻夆竝弻仸詺衭伕涘洢渟濦棐淸竼怌凕挴媦閈邉瀧皪俻飇驫玞羋汭潕懣潧灜肸瑉楩莑浃缳缗腼湴饽浡圤忄飨鳕蚝冖夲缬滪糢呅幈潣勱鳯雰儐癛靄顠辺籓牳涏澲霱禡瀨瞙冨浵渰澁溙洝峚仮屛鋙鋩嬤襬闬渕凖磻飊誁婄捗淓緋朏堏瀅俌姵饣踫鞶珻馷矇霺澦潄摓蕡霬媌漍椚騑涢繙郿鬽洐滃閔騛暜愽佫郈螨凄谝衤戅蹒鄤琀余闫岩邬玮岚贻峥娴娅嵘准恽鳌诒嫒祎韫瓯峤馀嬿怿娈奀顼砺璎瑷诩鹦鹉矶埙饴峄肴韪垲崟崃谙巅帏痖増璈骜袅邺岘岙垅岽郓奡舣鹜讴鸢壎埜垭嵚砜峣墡茔轾岖圹砻纡硃磑嵨诿骛嘤愠嶶砫塩崝媪怄嵝怃呓碛撄巖嶸岞圴嵎嗳嶒鲑坜谀堾硷欤鰲卾垿砕岆峳鱿垞肮卬鹳猬闱尓硖礧昻峇児埥峲嶢盦塏礪嶔崄塇垙堒峩垾壖碞罂碜鲔繶靥庑垆崂鄘硗瘾盫闇鮟醠謷爊巉崵氩鳙氲詒堢礒墷礇峷嶵岅垹埲峀睋砈磯礘蝁峼墪咡坬擜磀亜峏岋詻衈砨堊埡蚅巓墂埄崥醃媼嫯岰眑磝磽礉翶蝹嬡嵦懓懝敱敳昹曖欬毐塧壒阸隑鯦鱫鴱碪罯峕嵗隞驁鴁鴢塎崻嶫坮誐吘崓磖囮堮咢聏唲峉搕皒砐偽唖囐嶗岤岮硧嶤壄垁塣礈堗峾嶘垷嵷巘磒壡碔磳墸垗磘岧嶧堣硽砤砋峃塟巗圫壪碤磶圼嵵磦礩岹磰嵃墖岃矹嶮墌塮岝硏嵠巇磤峠塨垜妿堷塼碖磄崸塆垥磌圷砽嵔岉壀墝垶嶪嶑嵶峗岏嶾砓崳佮粫僫歞馤侒峖坿碏峵塯碨嵤塽峑坉岴磧厑伌儗呝嘊娾啀崣岟坄塋玵痷裺誝諳豻坒巊磎礃坁巌嵀礖崺礂嶨嶠謸軪郩镺獓坺垻墢嶴慠扷抝摮擙墽絠醷頞貋遃鴳鵪鶕馣岇垪硨碭崿覨廅珴姶偔琧弐臑匎胹侕峐啈峎悪吪嶡墎堝嬭嶁堈峺乯昷礱嶇嵐壢嶍崹埁嵄硤嵍壜埶垏塺硸坱坃崉垼礏碝墰碢岄礋塕塭砙墇壦嵡峴嶖堐碬壐峞巚峿礥嵞磫垔礯埑峫峂堟崱坣嵕嶎嶊堹峟嶬嵱埦碿崅磃堘壆壚垽崰塦崍鷔鼇埿坹塈堬坾垝硢硹諰譪譺賹躷嶚埣砡峱峅嵸儑匼咹堓婩屽塴嵭硆娿崢硣墛壝峓骯厫嗸嚻硺堫嵏堖搹墭嶀峮璦皧瞹硋噯堨巀乻堩堽袻筽腢塸塤巏嶦礢墿嶟崕矷毦隂隌鞌韽頇旕墵礜塐壧嵓崯礹坸壙譌碸碵嵉墕塒峹坧碒匽坢琙恹鼋羑鹌圡圠砗腌晻堛垩歺厈媕唵啽腤芺嶅垇墺嶓屵仒尒埚垴琟屲殒嵖屳峬弍訑塝墋觟妑壸圢邘


以上都是转换后没有笔画的字

Tack Chen ***@***.***> 于2022年5月2日周一 21:50写道：

**Comment by theajack** [comment]
会考虑加入后续更新计划，但是出于包体大小考虑 部分生僻字可能不会支持到或者通过插件方式支持

**Comment by theajack** [comment]
Fixed in v3.2.0
