### ISSUE TITLE
未收录拼音 den

### ISSUE THREAD

**Issue by jiangteng2019** [theajack/cnchar#224]
cnchar.spellToWord('den')  // 错误的拼音: den
且不支持api设置:
`cnchar.setSpell('扥', 'den4')`

**Comment by theajack** [comment]
感谢反馈 下个版本会加上这个汉字和拼音

**Comment by jiangteng2019** [comment]
未收录的拼音有：chua(欻) den(扥扽) eng(鞥) nun(黁) rua(挼) tei(忒) 。有些生僻字读音不确定，只有部分词典收录，请酌情添加。

**Comment by theajack** [comment]
Fixed in v3.2.0
