### ISSUE TITLE
鸟的默认读音能否调换一下

### ISSUE THREAD

**Issue by mingyigg** [theajack/cnchar#230]
目前鸟字默认读音是 diao3，好奇怪，一般都是读 niao3

**Comment by theajack** [comment]
感谢 指出 下个版本修复一下

**Comment by theajack** [comment]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/23377279/172269446-f732daa9-518d-4c58-9a73-e8ae968db216.png">
我看3.2.0 好像已经修复了

**Comment by mingyigg** [comment]
> <img alt="image" width="386" src="https://user-images.githubusercontent.com/23377279/172269446-f732daa9-518d-4c58-9a73-e8ae968db216.png">
> 
> 我看3.2.0 好像已经修复了

我也用的是3.2，不知道为什么你的是正确的，我的还是diao在前面
<img width="877" alt="截屏2022-06-11 18 27 36" src="https://user-images.githubusercontent.com/21259162/173184073-5c1d0045-113f-4de6-8309-209be59eab28.png">

是不是因为你没有启动多音字模式？我启用了多音字

cnchar.spell(_wordStr, 'poly', 'array', 'tone', 'low')

是不是多音字模式下，拼音是按照首字母顺序来排列的？

**Comment by mingyigg** [comment]
被字也是一样的，开启多音字以后，pi1在bei4前面，但是明显bei4这个读音是更常用的

在开启多音字模式下，能否让常用读音自动排在前面呢？

**Comment by theajack** [comment]
@mingyigg 
3.2.1已发布，已修复该问题
