### ISSUE TITLE
"胜"，用笔画拼不回去

### ISSUE THREAD

**Issue by FourNightsJason** [theajack/cnchar#231]
![image](https://user-images.githubusercontent.com/56989185/172089785-c46ca3b8-886b-4049-b51d-5f32877628e2.png)
如上图，”胜“字可以解构出的笔画，用解构出的笔画却拼不回去。

**Comment by theajack** [comment]
感谢指出，我看看

**Comment by theajack** [comment]
@FourNightsJason 
3.2.1已发布，已修复该问题

**Comment by FourNightsJason** [comment]
感谢大佬
