### ISSUE TITLE
cnchar-wrods 词组功能不太实用

### ISSUE THREAD

**Issue by mingyigg** [theajack/cnchar#232]
大佬辛苦了，cnchar-wrods 词组功能在实际应用的时候感觉不是很实用，我实际用的时候一般是传入一个汉字，查询相关联的词语，但是目前这个库存在的问题，一次性返回非常多的词语，但是大部分的词语都是很偏僻的用法，很不实用。如果能否按照使用频率返回常用的词语就更好了，当然使用频率这个估计很少有词库会统计。但是我觉得也是可以换一个词库的，相关词语不需要返回很多，只需要返回比较常用的那些就行了，我觉得应该会有类似的词库，因为很多汉字网站感觉返回的词语都是相关度比较高的

**Comment by theajack** [comment]
你是使用3.1.0 还是3.2.0 
如果是3.1.0可以到升到3.2.0 试试，3.2.0 换了一个更常用的词库
<img width="795" alt="image" src="https://user-images.githubusercontent.com/23377279/172268981-ebad4a1f-0a76-4890-a7ca-f853615d7b4d.png">

**Comment by mingyigg** [comment]
> 你是使用3.1.0 还是3.2.0 如果是3.1.0可以到升到3.2.0 试试，3.2.0 换了一个更常用的词库 <img alt="image" width="795" src="https://user-images.githubusercontent.com/23377279/172268981-ebad4a1f-0a76-4890-a7ca-f853615d7b4d.png">

试了一下确实好用多了，谢谢
