### ISSUE TITLE
cnchar-explain 能否支持单个字的解释

### ISSUE THREAD

**Issue by mingyigg** [theajack/cnchar#233]
目前这个库好像只支持词语的解释，能否返回单个字的解释呢？
我找了目前github有一个新华字典的词库，还有一个在此基础上改造的库，里面都有单个字的解释
不知道大佬有没有兴趣开发一下

https://github.com/pwxcoo/chinese-xinhua
https://github.com/mapull/chinese-dictionary

这个库是这么返回的

[
    {
        "word": "嗄",
        "oldword": "嗄",
        "strokes": "13",
        "pinyin": "á",
        "radicals": "口",
        "explanation": "嗄〈叹〉\n\n 同啊”。表示省悟或惊奇\n\n 嗄!难道这里是没有地方官的么?--宋·佚名《新编五代史平话》\n\n 嗄á叹词。在句首，〈表〉疑问或反问～，这是什么？～，你想干什么？\"嗄\"另见shà㈠。\n\n 嗄shà\n\n ⒈声音嘶哑～声。\n\n 嗄a 1.助词。表示强调﹑肯定或辩解。 2.助词。方言。表示疑问或反诘。\n\n 嗄xià 1.见\"嗄饭\"。 2.见\"嗄程\"。",
        "more": "嗄 ga、a 部首 口 部首笔画 03 总笔画 13  嗄2\nshà\n〈形〉\n(1)\n声音嘶哑的 [hoarse]\n终日嚎而嗌不嗄。--《老子》\n(2)\n又如嗄哑,嗄嘶(嗓音嘶哑)\n嗄\nshà\n〈叹〉\n(1)\n什么 [what]--表示否定\n我要丢个干干净,看你嗄法把我治。--清·蒲松龄《聊斋俚曲集》\n(2)\n旧时仆役对主人、下级对上级的应诺声 [yes]\n带进来”。两边军士应一声嗄”,即将牛皋推至面前。--《说岳全传》\n另见á\n嗄1\ná\n〈叹〉\n同啊”(á)。表示省悟或惊奇 [ah]\n嗄!难道这里是没有地方官的么?--宋·佚名《新编五代史平话》\n另见shà\n嗄1\nshà　ㄕㄚ╝\n嗓音嘶哑。\n郑码janr，u55c4，gbke0c4\n笔画数13，部首口，笔顺编号2511325111354\n嗄2\ná　ㄚˊ\n同啊2”。\n郑码janr，u55c4，gbke0c4\n笔画数13，部首口，笔顺编号2511325111354"
    },
    ... 
]

**Comment by theajack** [comment]
我看过这个词典太大了，打包到js里不太行
不过应该可以做成加载json，类似draw和voice包，这个后续考虑加入插件计划

**Comment by mingyigg** [comment]
> 我看过这个词典太大了，打包到js里不太行 不过应该可以做成加载json，类似draw和voice包，这个后续考虑加入插件计划

这个词典收藏的字好像有2w多个，确实很大，也许可以考虑一下先把常用的两三千个字做成js，然后提供一个方法允许用户切换数据源为加载json，相当于分成了常用版和扩展版。因为里面 [char_common_detail.json](https://github.com/mapull/chinese-dictionary/blob/main/data/character/char_common_detail.json)  这个json文件其实也才3.5M，是常用的3500个字，3.5M其实也还好

**Comment by theajack** [comment]
@mingyigg 
3.2.1已发布，已支持该功能

**Comment by mingyigg** [comment]
> @mingyigg 3.2.1已发布，已支持该功能

感谢
