### ISSUE TITLE
这个方法无效啊

### ISSUE THREAD

**Issue by yyj1983** [theajack/cnchar#238]
cnchar.info('汉字');

**Comment by theajack** [comment]
首先，版本要在3.2.0+
其次需要安装 cnchar-info 插件

![image](https://user-images.githubusercontent.com/23377279/180583671-6b17e32c-3938-4753-a85e-b5d1a19adc1e.png)

![image](https://user-images.githubusercontent.com/23377279/180583688-67fec42f-1ccc-4f9c-9c9c-ecb8a40389a2.png)

**Comment by yyj1983** [comment]
我调用时候，返回的是：[object Object]

**Comment by yyj1983** [comment]
[已经弄好。是我自己的问题。嘿嘿](https://s2.loli.net/2022/08/12/xGtagFVpjNERl6u.jpg)
