### ISSUE TITLE
transformTone 返回不正确的内容

### ISSUE THREAD

**Issue by hoythan** [theajack/cnchar#244]
```
cnchar.transformTone('peng4', true).spell   // pǐng
cnchar.transformTone('zi3', true).spell   // zū  
```

正确应该返回
```
péng
zǐ
```

**Comment by theajack** [comment]
@hoythan 感谢指正 下个版本修正

**Comment by theajack** [comment]
<img width="361" alt="image" src="https://user-images.githubusercontent.com/23377279/226111187-3afe51b6-2779-4716-aa32-804c2dbc5327.png">

是对的哈
