### ISSUE TITLE
按文档《自定义部署:离线使用》安装引用及设置 怎么没有效果呢？

### ISSUE THREAD

**Issue by ky2700** [theajack/cnchar#245]
<script type="text/ecmascript-6">
// 汉字拼音笔画js库
import cnchar from 'cnchar'
import draw from 'cnchar-draw'
cnchar.use(draw) // use 在浏览器环境中非必须
cnchar.setResourceBase('http://localhost:3002/')
// 默认导出
export default {
  components: {},
  props: {},
  data() {
    return {}
  },
  computed: {},
  created() {
    // 获取当前版本：
    let version = cnchar.version // string 类型
    console.log(`当前版本：${version}; 当前运行的环境：${cnchar.env}`)
  },
  mounted() {
    this.cncharDraw()
  },
  methods: {
    cncharDraw() {
      // draw('你好')
      cnchar.draw('你好', {
        el: '#drawNormal'
      })
    }
  }
}
</script>
本地 cnchar-serve 也启动了
![image](https://user-images.githubusercontent.com/7484559/200751176-d4964889-2b5a-4bf6-9535-e1731f182853.png)

怎么资源还是请求 unpkg 呢？
https://unpkg.com/cnchar-data@1.1.0/draw/%E5%A5%BD.json

**Comment by theajack** [comment]
@ky2700  需要修改一下 base，生产环境的话 需要修改成对应的你自己的服务地址

```js
cnchar.setResourceBase('http://localhost:{port}/')
```
