### ISSUE TITLE
测试代码遗留

### ISSUE THREAD

**Issue by iamcco** [theajack/cnchar#246]
https://github.com/theajack/cnchar/blob/3ceb2ea6999e084f65018e68fa8565ee4687b2f6/src/cnchar/plugin/input/associate/ass-spell.ts#L36

每次调用会多出不必要的 log

**Comment by theajack** [comment]
@iamcco 感谢 下个版本移除掉

**Comment by theajack** [comment]
v3.2.3 中已修正
