### ISSUE TITLE
论文中如何引用本项目

### ISSUE THREAD

**Issue by zhyongwei** [theajack/cnchar#247]
您好，项目的功能非常好，也非常有价值，感谢！我在一篇论文中引用了本项目，能否告知您的真实姓名（主要责任者）呢？电子文献具体的引用格式需符合以下规范：

> ［序号］主要责任者.题名：其他题名信息［文献类型标志/文献载体标志］.出版地：出版者，出版年(更新或修改日期)［引用日期］.获取和访问路径.
示例：
［1］萧钰.出版业信息化迈入快车道[EB/OL].(2001-12-19) [2002-04-15].http:∥www.creader.com/news/ 200112190019.htm.
［2］Online Computer Library Center,Inc.History of OCLC［EB/OL］.[2000-01-08].http:∥www.oclc.org/ about/history/default.htm.
［3］傅刚.大风沙过后的思考[N/OL].北京青年报，2000-04-12(14)[2002-03-06]. http:∥www.bjyouth.com.cn/Bqb/20000412/GB/4216%5ED0412B1401.htm.
［4］赵耀东.新时代的工业工程师[M/OL].台北:天下文化出版社，1998[1998-09-26].http://www.ie.nthu.edu.tw/info/ie.newie.htm.

谢谢您！

**Comment by theajack** [comment]
你好，感谢你的认可，可以这样引用 @zhyongwei 

［x］Tack Chen(2019).Cnchar[Source Code]. https:∥www.github.com/theajack/cnchar
