### ISSUE TITLE
cnchar.voice无法在苹果设备上播放

### ISSUE THREAD

**Issue by mxm145** [theajack/cnchar#252]
cnchar.voice无法在苹果设备上播放声音，控制台也没有报错，查看资源的时候发现错误，请问有什么解决办法吗？
![image](https://user-images.githubusercontent.com/869702/208012244-37766f71-b0e7-49a1-a193-33d2c123acd2.png)

**Comment by theajack** [comment]
@mxm145 这个不是bug哈 ios和macos需要在用户交互事件中调用才可以播放音频，请尝试在button click事件中调用
至于这个显示的资源载入错误可以忽略
