### ISSUE TITLE
idiom spell 模式下仅支持查询首个汉字的拼音

### ISSUE THREAD

**Issue by mapull** [theajack/cnchar#253]
升级到 3.2版本之后，发现出现了下面的提示：

idiom spell 模式下仅支持查询首个汉字的拼音

cnchar.idiom(['好','','',''])    -> 这样可以得到数据

cnchar.idiom(['','','好',''])  ->  模式下仅支持查询首个汉字的拼音

没有看到哪里有文档解释如何处理。

**Comment by theajack** [comment]
@mapull 
这应该是个bug 我看看

**Comment by theajack** [comment]
v3.2.3 中已修正
增加了 第二个参数 mode，详情见文档
