### ISSUE TITLE
spellToWord 部分情况下报错

### ISSUE THREAD

**Issue by mapull** [theajack/cnchar#254]
某些读音查汉字时出现问题：

`cnchar.spellToWord('dǐnɡ', 'array')`

cnchar.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'substr')
    at Object.spellToWord (cnchar.min.js:1:42861)
    at <anonymous>:1:8

大部分是可以的：
`cnchar.spellToWord('a', 'array')`

 ['呵', '啊']

**Comment by theajack** [comment]
好的 下个版本看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月1日(周三) 晚上9:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [theajack/cnchar] spellToWord 部分情况下报错 (Issue #254)




 
某些读音查汉字时出现问题：
 
cnchar.spellToWord('dǐnɡ', 'array')
 
cnchar.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'substr')
 at Object.spellToWord (cnchar.min.js:1:42861)
 at :1:8
 
大部分是可以的：
 cnchar.spellToWord('a', 'array')
 
&nbsp;['呵', '啊']

**Comment by theajack** [comment]
@mapull 
这里不支持直接使用音调，需要这么使用 `cnchar.spellToWord('dinɡ3', 'array')`

这个后续我加一下支持传入音调

**Comment by theajack** [comment]
还有你这里的 g 字符不太对

<img width="179" alt="image" src="https://user-images.githubusercontent.com/23377279/226097334-14efcab0-46b2-42d9-b754-4077bed6c046.png">

**Comment by theajack** [comment]
主要还是你传入的字符不对，传入音调也是可以的

<img width="315" alt="image" src="https://user-images.githubusercontent.com/23377279/226097428-4c1b4f58-9074-49fc-9b97-d97dce37c36c.png">
