### ISSUE TITLE
How to restart / reset animation with a command?

### ISSUE THREAD

**Issue by abathellier** [theajack/cnchar#257]
Hi,

I just want to restart the animation programmatically, for example: 

```tsx
<Button onClick={() => { writer.resetAnimation() } }>Restart</Button>
```

There are `startAnimation()`, `pauseAnimation()` and `resumeAnimation()` functions but i haven't found anything to do a restart. Is there a way to do this?

**Comment by theajack** [comment]
I'm sorry that there is no api that can do it for the time being, maybe you can call the draw method again. The next version will consider adding this feature. @durdenx

**Comment by theajack** [comment]
@durdenx add restartAnimation in v3.2.3
