### ISSUE TITLE
为什么“穎”字的笔画数是0？

### ISSUE THREAD

**Issue by xiaohong2022** [theajack/cnchar#258]
如题
![F12控制台测试图](https://user-images.githubusercontent.com/97574185/225892507-a6e8fdff-23b6-4934-b84d-a2dea2576db8.png)

**Comment by xiaohong2022** [comment]
我上网搜了下，这个字的笔画数是13

**Comment by theajack** [comment]
感谢反馈 下个版本补充一下 这个繁体字没有录入

**Comment by theajack** [comment]
<img width="417" alt="image" src="https://user-images.githubusercontent.com/23377279/225949874-0eb48045-c6ee-48f3-bc46-775daf5d6458.png">
有这个字的啊 笔画数是16，是颖字的繁体字，查询这个字需要安装 [cnchar-trad](https://shiyix.cn/cnchar/doc/trad.html) 插件

**Comment by xiaohong2022** [comment]
好吧谢谢

**Comment by xiaohong2022** [comment]
等等我用的是UNPKG引用，是不是没同步到UNPKG（）
