### ISSUE TITLE
[问题] "娘" 字读法

### ISSUE THREAD

**Issue by ben-alphabeans** [theajack/cnchar#260]
使用 spellToWord 用 “nian” 可以找到 “娘” 字，但 “niang“ 找不到
我们可以自定义或者载入自己的字库吗？

**Comment by theajack** [comment]
@ben-alphabeans 
自定义字库可以的
https://theajack.github.io/cnchar/doc/custom.html

但是这个问题来是一个bug, 娘字读音有误

**Comment by theajack** [comment]
v3.2.4 中已修复
