### ISSUE TITLE
希望能增加根据部首查询汉字的功能

### ISSUE THREAD

**Issue by mingyigg** [theajack/cnchar#261]
目前已经有能根据笔画数查询汉字的功能

我目前的使用场景碰到了需要根据部首查询汉字的需求，希望能够支持一下

非常感谢大佬的付出

**Comment by theajack** [comment]
@mingyigg v3.2.4中已增加 [文档](https://www.shiyix.cn/cnchar/doc/radical.html#_1-%E4%BB%8B%E7%BB%8D)

**Comment by bhargav-vasist** [comment]
@theajack The documentation link does not work. Could you check?
I'm in a similar situation trying to extend a library's functionality.
