### ISSUE TITLE
希望在cnchar-code中增加五笔码

### ISSUE THREAD

**Issue by mingyigg** [theajack/cnchar#262]
目前 cnchar-code 支持的编码方式有 二进制编码、charCode、unicode、url编码、gbk编码、四角编码、仓颉编码、统一汉字编码

不知道能否支持一下五笔码，感觉也是很常用的功能

**Comment by mingyigg** [comment]
https://github.com/a-fat-k79/k79-dict  这个仓库里是从百度汉语爬过来的汉字信息，有很全的五笔码，感觉大佬可以参考下呢 @theajack

**Comment by theajack** [comment]
不是从百度汉语爬的，五笔码在cnchar-input插件里已经有了&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月5日(周三) 中午12:05
收件人: ***@***.***&gt;;
抄送: "Tack ***@***.******@***.***&gt;;
主题: Re: [theajack/cnchar] 希望在cnchar-code中增加五笔码 (Issue #262)




 
https://github.com/a-fat-k79/k79-dict  这个仓库里是从百度汉语爬过来的汉字信息，有很全的五笔码，感觉大佬可以参考下呢 @theajack

**Comment by mingyigg** [comment]
嗯嗯，我不是说你的仓库说爬的，我是说我找到的这个仓库是爬的，可以参考。当然 input 里已经有了的话就可以直接用了，那更好了

> 不是从百度汉语爬的，五笔码在cnchar-input插件里已经有了&nbsp;
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年4月5日(周三) 中午12:05 收件人: ***@***.***&gt;; 抄送: "Tack ***@***.******@***.***&gt;; 主题: Re: [theajack/cnchar] 希望在cnchar-code中增加五笔码 (Issue #262) https://github.com/a-fat-k79/k79-dict 这个仓库里是从百度汉语爬过来的汉字信息，有很全的五笔码，感觉大佬可以参考下呢 @theajack — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

**Comment by theajack** [comment]
@mingyigg v3.2.4中已增加 [文档](https://www.shiyix.cn/cnchar/doc/code.html)
