### ISSUE TITLE
the api cnchar.input not work at v3.2.4

### ISSUE THREAD

**Issue by wangwenwen130** [theajack/cnchar#266]
![image](https://user-images.githubusercontent.com/48354328/231751371-a64253ba-a125-419a-8906-df87d54c81f6.png)
![image](https://user-images.githubusercontent.com/48354328/231751466-e6d8849d-5969-4a2f-bf9d-0d2fa6bbbbc2.png)

**Comment by theajack** [comment]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/23377279/232187339-414d199d-2cc6-42fe-90b7-671dce79c557.png">

需要前置引入 cnchar、cnchar-words

**Comment by wangwenwen130** [comment]
ok， thanks

**Comment by wangwenwen130** [comment]
> <img alt="image" width="578" src="https://user-images.githubusercontent.com/23377279/232187339-414d199d-2cc6-42fe-90b7-671dce79c557.png">
> 
> 需要前置引入 cnchar、cnchar-words

![image](https://user-images.githubusercontent.com/48354328/232771200-81f39052-fca0-4915-bd54-2ff07512fa7a.png)
![image](https://user-images.githubusercontent.com/48354328/232771413-63535626-19ca-4c52-9fc7-76291b9cf3bd.png)

您好，可以给一个详细的使用demo吗？
