### ISSUE TITLE
cnchar-code 会依赖 cnchar-input

### ISSUE THREAD

**Issue by mingyigg** [theajack/cnchar#267]
cnchar-code 新增了五笔码的功能，用的是 cnchar-input 里的数据，所以现在使用 cnchar-code 之前必须引入 cnchar-input 了，不然的会报错：TypeError: Cannot read property 'wubi' of undefined。
建议cnchar-code里独立添加一份五笔码数据，或者在文档中说明必须先引入cnchar-input

**Comment by theajack** [comment]
文档中 已经说明了

<img width="559" alt="image" src="https://user-images.githubusercontent.com/23377279/232187167-5e1768c0-63a6-4da1-aebf-812edd7fe2e9.png">

这里不考虑把五笔码字典独立放到cnchar-code中，会有冗余且不好维护，还有繁体字五笔码的逻辑
