### ISSUE TITLE
请问能不能通过笔顺，反推出相应文字结果数组呢？

### ISSUE THREAD

**Issue by bbzz7** [theajack/cnchar#4]
你好，中胜，请问能不能通过笔顺，反推出相应文字结果数组呢？或者你给点提示，我自己加一个这样的方法？

**Comment by theajack** [comment]
当然可以啊，你想要的输入的笔顺是什么形式的，我来加个接口。
另外，你咋知道我名字的？😂

**Comment by bbzz7** [comment]
我觉得从用户体验上，可能name参数的形式最直观吧，
比如：cnchar.orderToWord(['横','撇','捺']); // 大

另外，名字是从你的个人网站：https://www.theajack.com/resume 知道的呀😃

**Comment by theajack** [comment]
已加 `[cnchar.orderToWord](https://github.com/theajack/cnchar#53-%E7%AC%94%E7%94%BB%E5%BA%8F%E5%88%97%E6%8E%A8%E5%87%BA%E5%8E%9F%E6%B1%89%E5%AD%97)`

**Comment by theajack** [comment]
已加 [cnchar.orderToWord](https://github.com/theajack/cnchar#53-%E7%AC%94%E7%94%BB%E5%BA%8F%E5%88%97%E6%8E%A8%E5%87%BA%E5%8E%9F%E6%B1%89%E5%AD%97)

**Comment by bbzz7** [comment]
完美～✌
