### ISSUE TITLE
请问多音字如何使用？

### ISSUE THREAD

**Issue by cyz0919** [theajack/cnchar#5]
请问多音字参数是如何使用的，我调用的时候浏览器总是打印
CnChar Warning:以下参数被忽略:["poly"]
谢谢

**Comment by theajack** [comment]
那是因为你用了多音词功能（cnchr-poly）。这个功能会把多音字给覆盖掉。
这个时候要启用多音字功能，要使用origin参数
"长".spell('origin','poly','tone') // return (Zhǎng|Cháng)
详情请参考 [参数使用](https://github.com/theajack/cnchar#61-spell-%E5%8F%82%E6%95%B0)

**Comment by cyz0919** [comment]
> 那是因为你用了多音词功能（cnchr-poly）。这个功能会把多音字给覆盖掉。
> 这个时候要启用多音字功能，要使用origin参数
> "长".spell('origin','poly','tone') // return (Zhǎng|Cháng)
> 详情请参考 [参数使用](https://github.com/theajack/cnchar#61-spell-%E5%8F%82%E6%95%B0)

非常感谢，应该是我没看明白文档

**Comment by theajack** [comment]
api设计也有问题，后续会考虑去除 origin 参数

**Comment by cyz0919** [comment]
> api设计也有问题，后续会考虑去除 origin 参数

建议可以考虑这样一个需求，返回的拼音声母、韵母分开，如果是整体认读音节不分

**Comment by theajack** [comment]
好的 加入需求计划

**Comment by freedomgzh** [comment]
您是通过什么方式向我发邮件呢，很有意思的互动




------------------ 原始邮件 ------------------
发件人: "theajack"<notifications@github.com>;
发送时间: 2019年9月30日(星期一) 下午2:23
收件人: "theajack/cnchar"<cnchar@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [theajack/cnchar] 请问多音字如何使用？ (#5)




api设计也有问题，后续会考虑去除 origin 参数

**Comment by theajack** [comment]
我是在github上面回复issue的。。star的人都看得到吗？

**Comment by freedomgzh** [comment]
yes，至少我看到了，我应该是star了这个组件


------------------ 原始邮件 ------------------
发件人: "theajack"<notifications@github.com>;
发送时间: 2019年9月30日(星期一) 下午2:46
收件人: "theajack/cnchar"<cnchar@noreply.github.com>;
抄送: "桀骜"<519668307@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [theajack/cnchar] 请问多音字如何使用？ (#5)




我是在github上面回复issue的。。star的人都看得到吗？

**Comment by cyz0919** [comment]
还有个问题，不知道多音字的词组是如何处理的，”长宽“返回的值不正确
console.log(cnchar.spell('成长','array','tone','low'))
["chéng", "zhǎng"]

console.log(cnchar.spell('长城','array','tone','low'))
["cháng", "chéng"]

console.log(cnchar.spell('长宽','array','tone','low'))
["zhǎng", "kuān"]

**Comment by theajack** [comment]
是通过多音词词典查询获取的
准确区别多音词需要大量词库和分词支持，web上一个js库达不到准确识别多音词的功能，我找的词库不够全。但是词库太大又会导致js文件过大，加载过慢的问题。
我发现有问题的多音词我一直在往词典里面加，这个 '长宽' 我后续会加进去，或者你也可以把发现不支持的多音词自己加进去，代码在 /src/plugin/poly/polyphone-phrase-simple.json 中； 然后发起一个push请求

**Comment by cyz0919** [comment]
> 是通过多音词词典查询获取的
> 准确区别多音词需要大量词库和分词支持，web上一个js库达不到准确识别多音词的功能，我找的词库不够全。但是词库太大又会导致js文件过大，加载过慢的问题。
> 我发现有问题的多音词我一直在往词典里面加，这个 '长宽' 我后续会加进去，或者你也可以把发现不支持的多音词自己加进去，代码在 /src/plugin/poly/polyphone-phrase-simple.json 中； 然后发起一个push请求

明白，辛苦了
