### ISSUE TITLE
能不能提供typescript相应的类型声明文件

### ISSUE THREAD

**Issue by liudonghua123** [theajack/cnchar#9]
这个项目非常不错，但是在typescript中使用的时候会提示
```
Try `npm install @types/cnchar` if it exists or add a new declaration (.d.ts) file containing `declare module 'cnchar';`
```
等错误信息，希望能够提供类型信息文件

**Comment by theajack** [comment]
好的，考虑加入下个版本计划

**Comment by theajack** [comment]
> 这个项目非常不错，但是在typescript中使用的时候会提示
> 
> ```
> Try `npm install @types/cnchar` if it exists or add a new declaration (.d.ts) file containing `declare module 'cnchar';`
> ```
> 
> 等错误信息，希望能够提供类型信息文件

好的，考虑加入下个版本计划

**Comment by theajack** [comment]
> 这个项目非常不错，但是在typescript中使用的时候会提示
> 
> ```
> Try `npm install @types/cnchar` if it exists or add a new declaration (.d.ts) file containing `declare module 'cnchar';`
> ```
> 
> 等错误信息，希望能够提供类型信息文件

已加入 typescript 类型声明文件，请升级到 2.0.6 是试用

**Comment by liudonghua123** [comment]
@theajack 非常感谢！ 😃
